### ISSUE TITLE
Please Fix the density

### ISSUE THREAD

**Issue by ghluuuuuu** [ashwinr64/android_device_xiaomi_oxygen#4]
The XiaoMi Max2 Display PPI is 342 ,
but in the [cm-14.1-redo],
The "system.prop" is set

`ro.sf.lcd_density=480`

I suggest setting it to

`ro.sf.lcd_density=342`

**Comment by ashwinr64** [comment]
Stock sets it to 480, and it looks pretty correct.

**Comment by ghluuuuuu** [comment]
All right...
